### ISSUE TITLE
sh download.sh Error

### ISSUE THREAD

**Issue by BD-MF** [cliang1453/super-structured-lottery-tickets#1]
python: can't open file 'scripts/download_glue_data.py': [Errno 2] No such file or directory

**Comment by cliang1453** [comment]
Hi, 

It looks like the the dependent repo has been updated. You can replace https://github.com/cliang1453/super-structured-lottery-tickets/blob/caad8b6618831cfde9ba764bfe27ab7564dfda60/download.sh#L30-L37 with

```
## DOWNLOAD GLUE DATA
## Please refer glue-baseline install requirments or other issues.
git clone https://github.com/nyu-mll/jiant-v1-legacy.git
cd jiant-v1-legacy
python scripts/download_glue_data.py --data_dir $DATA_DIR --tasks all

cd ..
rm -rf jiant-v1-legacy
```
